### ISSUE TITLE
About the data set

### ISSUE THREAD

**Issue by nicedinner** [ashgeek/Ethracer#1]
Dear authors.  After downloading the data set, we discover that the processed contract is 8139 and the contracts have reported results is 6943. However, the buggy contracts number in the reports is 940. We would like to know if the 940 contains all 789 bugs in the paper?  What's the relation between them?  Can I have the exact data as presented in the paper ? Really need to know for further research. Thanks a lot!

**Comment by aashishkolluri** [comment]
Hi @nicedinner ,

Thank you for your interest in our work. It has been 2.5 years since I looked at this, so, I do not remember all the details at this point. I remember that we sampled about 5000 contracts and then reported results on them. So the 789 is most probably a subset of the 940 buggy contracts.
